# Site wide configuration

title:            Sebastián A. Pardo
locale:           en_CA
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
#  - jekyll-pandoc
#  - jekyll-pandoc-multiple-formats

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

pandoc:
  extensions:
    - smart
    - mathjax
    - csl: _styles/ch.csl
    - bibliography: ~/Documents/bib/library.bib

#pandoc:
#  skip: false
#  impose: false
#  output: ./tmp
#  flags: '--smart --parse-raw --csl=_styles/jpp.csl --bibliography=/home/mavzz/Documents/bib/library#.bib'
#  site_flags: '--toc'
#  outputs:
#    pdf: '--latex-engine=pdflatex'
#    epub:
#    markdown: 


# Site owner
owner:
  name: Sebastián Pardo
  avatar: sebphoto2.jpg
  bio: "PhD student at SFU: life history relationships and extinction risk in sharks, rays, and chimaeras"
  email: spardo@sfu.ca
  disqus-shortname: 
  twitter: sebpardo
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: sebpardo
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
